version: 2
jobs:
  ding:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "npm installing"
      - run: npm install
      - run: CI=true npm run build
  dang:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "Double trouble"
workflows:
  version: 2
  ding_dang:
    jobs:
      - ding
      - dang
